services:
  comfyui:
    build: .
    image: comfyui:latest
    container_name: comfyui
    ports:
      - "8188:8188"
    volumes:
      - ./storage/models:/ComfyUI/models
      - ./storage/comfy-input:/ComfyUI/input
      - ./storage/comfy-output:/ComfyUI/output
      - ./storage/comfy-custom_nodes:/ComfyUI/custom_nodes
      - ./storage/comfy-user:/ComfyUI/user
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 20G
