services:
  comfyui:
    build: .
    image: comfyui:latest
    container_name: comfyui
    ports:
      - "8188:8188"
    volumes:
      - ./storage/models:/app/ComfyUI/models
      - ./storage/comfy-input:/app/ComfyUI/input
      - ./storage/comfy-output:/app/ComfyUI/output
      - ./storage/comfy-custom_nodes:/app/ComfyUI/custom_nodes
      - ./storage/comfy-user:/app/ComfyUI/user
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 20G
